//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTarefa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Tarefa
    {
        public int IDTarefa { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataTarefa { get; set; }
        public Nullable<int> IDUSU { get; set; }
    
        public virtual Tb_Usuario Tb_Usuario { get; set; }
    }
}
